<%@ Page Language="C#" MasterPageFile="~/Views/Shared/About.Master" Inherits="System.Web.Mvc.ViewPage" %>
<asp:Content ContentPlaceHolderID="titleContentAbout" runat="server">Management</asp:Content>
<asp:Content ContentPlaceHolderID="AboutContent" runat="server">
<div class="breadcrumbs"><%= Html.ActionLink("Home", "", "", null, new { title = "Home" })%> > <%= Html.ActionLink("About", "Index", "about", null, new { title = "About" })%> > <%= Html.ActionLink("Management", "management", "about", null, new { title = "Management" })%></div>
<h1>Management</h1>
<h2>Zach Statham</h2>
<h3>Team President</h3>
<p><asp:Image class="imgBorder" ImageUrl="~/content/images/home-side.jpg" AlternateText="" GenerateEmptyAlternateText="true" Width="100" Height="130" ImageAlign="Right" runat="server" />Zach Statham is in his second term as Kennesaw State University Lacrosse Club President. He was a unanimous choice after his first term. He is a very focused, organized leader who leads by example paying attention to details. In addition to his administrative duties as lacrosse club President, Zach was chosen to be the Chairman of all club sports at KSU. This demands many addition hours dedicated to the thirteen other campus club sports. On the field in 2007 Zach earned the "Coaches Award of Excellence" for his hard work and tireless effort. In 2008 he earned Second Team honors in the Southeastern Lacrosse Conference as a defenseman and was KSU's first Academic All-American for his scholarly grades studying finance.</p>
<h2>Ken Byers</h2>
<h3>Head Coach</h3>
<p><asp:Image class="imgBorder" ImageUrl="~/content/images/home-side.jpg" AlternateText="" GenerateEmptyAlternateText="true" Width="100" Height="130" ImageAlign="Right" runat="server" />Building a successful and competitive collegiate program is no easy task. Coach Byers has the background and experience to accomplish both. His KSU career record is 21-18 and he has coached five All Southeastern Conference players. Before his tenure at KSU, Ken started the program at Etowah High School. During that time, Etowah compiled a record of 44-24 and became an elite team in the North Georgia Lacrosse League. He was an assistant coach at Roswell HS from 1999-2001, earning a public HS Championship in 1999. From 1982-2002 he was a player/coach for the Atlanta Lacrosse Club. He produced an overall team record of 307 wins and 104 losses. During that time the ALC earned numerous league titles and tournament championships. He was recognized in 1992 as "Coach of the Year" by the Southeastern Lacrosse League. From 1991-1996 he participated as an Editorial Board member for Lacrosse Magazine. He played lacrosse for national junior college powerhouse Suffolk Community College on Long Island and then finished collegiate career as a defenseman at Kutztown State in Pennsylvania. Ken still plays competitive lacrosse in national tournament s at the masters and grand masters level. Coach Byers is a member of the Positive Coaching Alliance and has been a certified lacrosse official. On January 28, 2007 Coach Byers was inducted into the Georgia Lacrosse Hall of Fame for his outstanding accomplishments to the sport of lacrosse in the state of Georgia. Ken has served the citizens of Atlanta, Georgia for the past twenty seven years with the Atlanta Fire Rescue Department. He has achieved the rank of Battalion Chief working out of the busy downtown area of Atlanta. He is married to his wife Kelly and they have two children, Jennifer and Bryan.</p>
<h2>Mark Stopher</h2>
<h3>Assistant Coach</h3>
<p><asp:Image class="imgBorder" ImageUrl="~/content/images/home-side.jpg" AlternateText="" GenerateEmptyAlternateText="true" Width="100" Height="130" ImageAlign="Right" runat="server" />Mark Stopher returns to the KSU sidelines after his 2008 debut. Coach Stopher will be assigned the defensive responsibilities for the Owls this year. Mark grew up an All- County player for Jamesville DeWitt High School in New York. He attended Syracuse University playing close defense from 1986 to 1989. He earned All-American honors 1988 and 1989. In those same years, Mark won the Division 1 National Championship for the Orangemen with teammates Gary and Paul Gait. He currently is a member of the Atlanta Lacrosse Club. His wife Brenda works in the Athletic Department at Kennesaw State University. They have two children, Brianna 7 and Zachery 5.</p>
</asp:Content>