<%@ Page Language="C#" MasterPageFile="~/Views/Shared/About.Master" Inherits="System.Web.Mvc.ViewPage" %>
<asp:Content ContentPlaceHolderID="titleContentAbout" runat="server">History</asp:Content>
<asp:Content ContentPlaceHolderID="AboutContent" runat="server">
<div class="breadcrumbs"><%= Html.ActionLink("Home","","", null, new { title="Home" })%> > <%= Html.ActionLink("About", "Index", "about", null, new { title = "About" })%> > <%= Html.ActionLink("History", "history", "about", null, new { title = "History" })%></div>
<h1>History</h1>
<p>In the Fall of 2005, three Kennesaw State University students Brett Davies, Anthony Grazanti, and Mike McCabe discussed the possibility of developing a lacrosse team for the school. The KSU Lacrosse Club was established before the end of the Fall Semester. The club began competiting during the Spring of 2006. Brett Davies was the first club President and Tara Parker was the faculty advisor from the University. Long time Atlanta high school coach Ken Byers accepted the position as Head Coach at KSU.</p>
<p>In 2006, the Owls started practicing and played a 12 game schedule. The first season had 23 players on the roster. The Lax Owl's first ever game was a 19-7 loss to the powerful Auburn Tigers in Auburn, Alabama. The first Kennesaw State University goal was scored by midfielder Robert Witt and was assisted by Alex Beasley. The goalkeeper for the first game was Wills Beadle. KSU won its first ever game on February 12, 2006 against The Citadel when they defeated the Bulldogs 15-8. That season the Owls went on to finish their inaugural season win a record of 8-4. The 2006 squad also recorded the program&#8217;s one and only shutout by defeating the University of Alabama 15-0. It was the important start that the team needed and the team made a big impression on other teams within the South Eastern Lacrosse Conference.</p>
<p>In 2007, the KSU Lax Owls were approved for competition within the SELC by unamanious vote. Their roster included 25 players and they produced a record of 8-6. Brett Davies finished his second term as Club President and his vision of a successful lacrosse program for KSU was now a reality. The team elected Zack Statham as Club President at the end of the 2007 season. Two KSU athletes earned individual recognition from the SELC in 2007. Jeremy Douthit earned honorable mention for his attack play and Robert Witt was named as a first team SELC midfielder for his outstanding effort for the Owls.</p>
<p>The 2008 season proved to be a reality check for the KSU program. The players and coaches scheduled a very aggressive schedule against many highly ranked lacrosse programs. Eight of the Owls thirteen opponents held a Top 20 ranking sometime during the 2008 season. The roster grew to 30 players but their record suffered. The team finished 5-8 that year. Many of the younger players got valuable experience during the season that would prove fruitful the following year. Three Owl players were selected for SELC honors. Zack Statham named to the SELC Defensive Second Team, Charles Roland was named as an honorable mention midfielder, and Kyle Hansen earned honorable mention honors for his goalie play. The team&#8217;s greatest achievement was being named &#8220;Best Club Sports Team&#8221; by the University. This is an honor that is bestowed to the most outstanding sports club organization among the thirteen competing sports club teams at KSU. It was truly a great finish to a tough year for the Owls.</p>
<p>2009 proved to be a break through year for the KSU program. The team improved its record to 11-2. The roster swelled to 33 players and the Owls were a solid and competitive team week in and week out. For a second consecutive year the program earned &#8220;Best Club Sports Team&#8221; on campus. This was truly an amazing feat considering all the other competitive groups this club beat out for the award for a second straight year. Two term club President Zack Statham passed the leadership torch to Junior Charles Roland. In 2009, KSU&#8217;s Scott Schulze was honored as a Men&#8217;s Collegiate Lacrosse Association All-American. He was also selected by the SELC as the &#8220;Offensive Player of the Year&#8220; and an SELC first team player. Junior Midfielder Charles Roland was also named to the SELC first team. Zack Statham earned honorable mention for his defensive play. Ken Byers was chosen by his fellow coaches as South Eastern Lacrosse Conference &#8220;Coach of the Year&#8221; in 2009 for his efforts bringing the program to national recognition. For the first time in the team&#8217;s history, the Owls held positions in both the MCLA and in the Collegelax.com National Top 20 polls. The Owls finished Twelveth in the laxpower.com poll last season.</p>
</asp:Content>