<%@ Page Language="C#" MasterPageFile="~/Views/Shared/About.Master" Inherits="System.Web.Mvc.ViewPage" %>
<asp:Content ContentPlaceHolderID="titleContentAbout" runat="server">Management</asp:Content>
<asp:Content ContentPlaceHolderID="AboutContent" runat="server">
<div class="breadcrumbs"><%= Html.ActionLink("Home", "", "", null, new { title = "Home" })%> > <%= Html.ActionLink("About", "Index", "about", null, new { title = "About" })%> > <%= Html.ActionLink("Management", "management", "about", null, new { title = "Management" })%></div>
<h1>Management</h1>
<h2>Anthony Grizanti</h2>
<h3>Head Coach</h3>
<p><asp:Image class="imgBorder" ImageUrl="~/content/images/home-side.jpg" AlternateText="" GenerateEmptyAlternateText="true" Width="100" Height="130" ImageAlign="Right" runat="server" />Head Coach Anthony Grizanti is a native of Liverpool, NY, a suburb of Syracuse, NY. Coach Grizanti earned two varsity letters playing high school football and lacrosse for Liverpool High School. Coach Grizanti started his junior and senior year for the Warriors as a defensive midfielder. In his senior year, he was awarded the coveted LHS Head, Heart, and Hustle Award.</p><p>After high school, Coach Grizanti attended Kennesaw State University. During his freshman and sophomore years, with the help of several other students, Coach Grizanti started the KSU lacrosse team. During his sophomore year, he played attack and midfield, and was the teams third leading scorer. After a short career with KSU, Coach Grizanti returned home to New York and concluded his college studies at NCAA division three Utica College. While at Utica, Coach Grizanti earned two varsity letters in lacrosse as a starting defensive midfielder his senior year.</p><p>After graduating from Utica College with a BS in Criminal Justice, Coach Grizanti moved to Dallas, Texas. In Dallas he served as the head coach of the Highland Park High School junior varsity team. He was also an assistant midfield coach for the Highland Park High School varsity team. In 2010, Coach Grizanti returned to KSU as an assistant coach. After two years working as an assistant coach, Coach Grizanti was elevated to head coach in 2012.</p><p>In Coach Grizanti's first season as head coach, the Owls secured an 8-5 record, playing the hardest schedule in KSU lacrosse history. The Owls were ranked in the top 20 throughout the entire season and advanced to the SELC Championship Game. The Owls finished the season as the SELC Tournament runner ups.</p><p>Coach Grizanti lives in Kennesaw with his fiancé Amber. They plan to marry after the conclusion of the 2013 season in Syracuse, NY.</p>
<br/>
<h2>Kevin Yelken</h2>
<h3>Coach</h3>
<p>Coach Yelken grew up on the farm in western Nebraska where he was a multisport letterman in High School. He went on to play football and run track at Nebraska Wesleyan University, graduating in 1981 with a degree in Political Science and Education. He spent 8 and half years in the United States Air Force as a pilot and is currently employed by Delta Air Lines as a Captain on the MD 88 aircraft. Over the years he has coached a multitude of youth and high school sports including baseball, basketball, track, and 7 years of high school lacrosse for both boys and girls. He spent years as a Den and Pack leader with the Boy Scouts and has been an active member of the Men's Ministry at Fellowship Bible Church in Roswell. Coach Yelken brings his years of leadership to the team now in his fourth season. He looks at coaching like this, "Sport is about life skills, if we develop good leaders for our boardrooms, responsible men for our community, and engaged fathers for our homes then we will probably win a few lacrosse games along the way."</p>
</asp:Content>